#!/usr/bin/env bash
#
# build_book.sh - Build the Practical Embeddings book
#
# Usage:
#   ./scripts/build_book.sh [version]
#   ./scripts/build_book.sh bump-patch|bump-minor|bump-major
#   ./scripts/build_book.sh --clean
#   ./scripts/build_book.sh --check
#   ./scripts/build_book.sh --help

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
TEX_DIR="${PROJECT_ROOT}/tex"
MAIN_FILE="embedding-book"
VERSION_FILE="${PROJECT_ROOT}/VERSION-book"
OUTPUT_DIR="${PROJECT_ROOT}/pdf-releases"
OUTPUT_NAME="Practical-Embeddings"

# Prepend TeX binaries to PATH (BasicTeX / MacTeX default location)
export PATH="/Library/TeX/texbin:${PATH}"

# ─── colours ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info()    { echo -e "${BLUE}==>${NC} $*"; }
log_success() { echo -e "${GREEN}✓${NC} $*"; }
log_warn()    { echo -e "${YELLOW}!${NC} $*"; }
log_error()   { echo -e "${RED}✗${NC} $*" >&2; }

# ─── version helpers ──────────────────────────────────────────────────────────
read_version() {
    if [[ -f "${VERSION_FILE}" ]]; then
        tr -d '\n' < "${VERSION_FILE}"
    else
        echo "0.1.0"
    fi
}

write_version() {
    echo "$1" > "${VERSION_FILE}"
    log_success "Version updated to $1"
}

bump_version() {
    local bump_type=$1
    local ver=$2
    if [[ ! $ver =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
        log_error "Invalid version format: ${ver}"
        exit 1
    fi
    local major="${BASH_REMATCH[1]}"
    local minor="${BASH_REMATCH[2]}"
    local patch="${BASH_REMATCH[3]}"
    case $bump_type in
        bump-major) echo "$((major+1)).0.0" ;;
        bump-minor) echo "${major}.$((minor+1)).0" ;;
        bump-patch) echo "${major}.${minor}.$((patch+1))" ;;
        *)
            log_error "Unknown bump type: ${bump_type}"
            exit 1
            ;;
    esac
}

# ─── version.tex ──────────────────────────────────────────────────────────────
generate_version_tex() {
    local version=$1
    local date
    date=$(date +"%B %Y")
    cat > "${TEX_DIR}/version.tex" <<EOF
% Auto-generated — do not edit by hand (regenerated by scripts/build_book.sh)
\newcommand{\bookversion}{${version}}
\newcommand{\bookdate}{${date}}
EOF
    log_success "Generated tex/version.tex  (v${version}, ${date})"
}

# ─── check dependencies ───────────────────────────────────────────────────────
check_deps() {
    local ok=1
    echo "Checking dependencies..."

    if command -v xelatex &>/dev/null; then
        log_success "xelatex found: $(xelatex --version 2>&1 | head -1)"
    else
        log_error "xelatex not found"
        log_info  "  macOS: brew install --cask mactex-no-gui"
        log_info  "  macOS: brew install --cask basictex  (then: sudo tlmgr update --self && sudo tlmgr install collection-xetex)"
        log_info  "  Or install from: https://tug.org/mactex/"
        ok=0
    fi

    if command -v pdfinfo &>/dev/null; then
        log_success "pdfinfo found (page counts will be reported)"
    else
        log_warn "pdfinfo not found (install poppler for page counts: brew install poppler)"
    fi

    if [[ $ok -eq 0 ]]; then
        log_error "Missing required dependencies"
        exit 1
    fi
    log_success "All required dependencies present"
}

# ─── clean ────────────────────────────────────────────────────────────────────
clean_build() {
    log_info "Cleaning LaTeX build artifacts..."
    cd "${TEX_DIR}"
    rm -f *.aux *.log *.out *.toc *.pdf
    cd "${TEX_DIR}/chapters"
    rm -f *.aux
    log_success "Clean complete"
}

# ─── build pdf ────────────────────────────────────────────────────────────────
build_pdf() {
    local version=$1
    cd "${TEX_DIR}"

    log_info "Running XeLaTeX pass 1/2..."
    if ! xelatex -interaction=nonstopmode "${MAIN_FILE}.tex" > build.log 2>&1; then
        # XeLaTeX sometimes exits non-zero even when a PDF is produced; check for file
        if [[ ! -f "${MAIN_FILE}.pdf" ]]; then
            log_error "XeLaTeX pass 1 failed — no PDF produced"
            log_info  "Last 30 lines of build.log:"
            tail -30 build.log
            return 1
        fi
        log_warn "XeLaTeX pass 1 exited with errors but produced a PDF (check build.log)"
    fi

    log_info "Running XeLaTeX pass 2/2  (TOC + cross-references)..."
    if ! xelatex -interaction=nonstopmode "${MAIN_FILE}.tex" >> build.log 2>&1; then
        if [[ ! -f "${MAIN_FILE}.pdf" ]]; then
            log_error "XeLaTeX pass 2 failed — no PDF produced"
            log_info  "Last 30 lines of build.log:"
            tail -30 build.log
            return 1
        fi
        log_warn "XeLaTeX pass 2 exited with errors but produced a PDF (check build.log)"
    fi

    if [[ ! -f "${MAIN_FILE}.pdf" ]]; then
        log_error "Build completed but PDF not found — check tex/build.log"
        return 1
    fi

    log_success "PDF built: tex/${MAIN_FILE}.pdf"
}

# ─── publish ──────────────────────────────────────────────────────────────────
publish_pdf() {
    local version=$1
    mkdir -p "${OUTPUT_DIR}"

    local versioned="${OUTPUT_DIR}/${OUTPUT_NAME}-v${version}.pdf"
    local latest="${OUTPUT_DIR}/${OUTPUT_NAME}-latest.pdf"

    cp "${TEX_DIR}/${MAIN_FILE}.pdf" "${versioned}"
    ln -sf "${OUTPUT_NAME}-v${version}.pdf" "${latest}"

    log_success "Published:  ${versioned}"
    log_success "Symlink:    ${latest}"
    ls -lh "${versioned}"

    if command -v pdfinfo &>/dev/null; then
        local pages
        pages=$(pdfinfo "${versioned}" 2>/dev/null | awk '/^Pages:/{print $2}')
        [[ -n "$pages" ]] && log_info "Pages: ${pages}"
    fi
}

# ─── show help ────────────────────────────────────────────────────────────────
show_help() {
    cat <<EOF
build_book.sh — Build the Practical Embeddings book

Usage:
  ./scripts/build_book.sh              # build with current version
  ./scripts/build_book.sh 1.2.3        # build with explicit version
  ./scripts/build_book.sh bump-patch   # increment patch, then build
  ./scripts/build_book.sh bump-minor   # increment minor, then build
  ./scripts/build_book.sh bump-major   # increment major, then build
  ./scripts/build_book.sh --clean      # remove LaTeX artifacts
  ./scripts/build_book.sh --check      # verify LaTeX is installed
  ./scripts/build_book.sh --help       # this message

Output:
  pdf-releases/${OUTPUT_NAME}-v<version>.pdf
  pdf-releases/${OUTPUT_NAME}-latest.pdf  (symlink)

Version is stored in:  VERSION-book
EOF
}

# ─── main ─────────────────────────────────────────────────────────────────────
main() {
    local arg="${1:-}"

    case $arg in
        --help|-h)
            show_help
            exit 0
            ;;
        --clean)
            clean_build
            exit 0
            ;;
        --check)
            check_deps
            exit 0
            ;;
    esac

    # Resolve version
    local version
    if [[ -z "$arg" ]]; then
        version=$(read_version)
        log_info "Using current version: ${version}"
    elif [[ "$arg" =~ ^bump- ]]; then
        local old
        old=$(read_version)
        version=$(bump_version "$arg" "$old")
        log_info "Bumping version: ${old} → ${version}"
        write_version "${version}"
    elif [[ "$arg" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
        version="$arg"
        log_info "Using specified version: ${version}"
        write_version "${version}"
    else
        log_error "Unrecognised argument: ${arg}"
        show_help
        exit 1
    fi

    echo

    generate_version_tex "${version}"
    echo

    build_pdf "${version}"
    echo

    publish_pdf "${version}"
    echo

    log_success "Done — ${OUTPUT_NAME} v${version}"
}

main "$@"
